
name: 京东神仙书院(至2月5日)

on:
  workflow_dispatch:
  schedule:
    - cron: '40 0 * * *'
  # watch:
  #   types: started
  # repository_dispatch:
  #   types: js_name
    
jobs:
  run-NodeJS:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: 'master'
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: install npm
        run: npm install
      - name: '运行 【京东神仙书院】'
        run: |
             node jd_immortal.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
          JD_IMMORTAL_LATLON: ${{ secrets.JD_IMMORTAL_LATLON }}
          JDSXSY_SHARECODES: ${{ secrets.JDSXSY_SHARECODES }}
